##############################################
# Datos a rellenar
##############################################

title: Entre Bambalinas

description: The translation must go on

social:
   github: entrebambalinas
   twitter: ebambalinasfake
   facebook: entrebambalinasfake
   email: rr.ss.entrebambalinas@gmail.com

# En esta lista podéis personalizar el orden de las páginas:
navigation:
 - title: Nosotros
   url: /nosotros
 - title: Equipo
   url: /equipo
 - title: Servicios
   url: /servicios
 - title: Porfolio
   url: /clientes
 - title: Valores
   url: /valores
 - title: Trabaja con nosotros
   url: /unete
 - title: Contacto
   url: /contacto

##############################################
# Cosas técnicas a partir de aquí
##############################################

url: https://entrebambalinas.github.io
baseurl: ""
paginate_path: "blog/p:num/"
permalink: pretty

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
